-- Keep physical inventory separate from the deliberately limited website
-- allocation. New horizon rows inherit the room's web-allocation setting.

alter table public.physical_rooms
  add column web_allocation_enabled boolean not null default false;

create or replace function public.apply_room_web_allocation_to_new_allotment()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  -- Inventory generated by onboarding/repair is closed unless its physical
  -- room belongs to the persistent web pool. Ad-hoc regression fixtures that
  -- do not use an inventory generation run retain the table's normal default.
  if not exists (
    select 1
    from public.inventory_generation_runs igr
    where igr.hotel_id = new.hotel_id
  ) then
    return new;
  end if;

  select pr.web_allocation_enabled
  into new.is_available
  from public.physical_rooms pr
  where pr.id = new.room_id
    and pr.hotel_id = new.hotel_id;

  new.is_available := coalesce(new.is_available, false);
  return new;
end;
$$;

create trigger physical_room_allotments_inherit_web_allocation
before insert on public.physical_room_allotments
for each row
execute function public.apply_room_web_allocation_to_new_allotment();

create or replace function public.publish_initial_web_allocation(
  p_room_numbers text[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_hotel_id uuid;
  v_operational_date date;
  v_end_date_exclusive date;
  v_requested_count integer;
  v_matched_count integer;
  v_affected_rows integer;
begin
  v_hotel_id := public.current_staff_hotel_id();

  if v_hotel_id is null then
    raise exception using
      errcode = '42501',
      message = 'An active staff profile is required.';
  end if;

  if not public.staff_has_any_role(
    array['admin', 'manager']::public.staff_role[]
  ) then
    raise exception using
      errcode = '42501',
      message = 'Only an admin or manager can publish the opening web allocation.';
  end if;

  if p_room_numbers is null or cardinality(p_room_numbers) = 0 then
    raise exception 'At least one website room is required.';
  end if;

  select count(distinct upper(btrim(room_number)))
  into v_requested_count
  from unnest(p_room_numbers) as requested(room_number)
  where nullif(btrim(room_number), '') is not null;

  if v_requested_count <> cardinality(p_room_numbers) then
    raise exception 'Website room numbers must be non-blank and unique.';
  end if;

  select count(*)
  into v_matched_count
  from public.physical_rooms pr
  where pr.hotel_id = v_hotel_id
    and pr.is_active
    and upper(pr.room_number) = any(
      select upper(btrim(room_number))
      from unnest(p_room_numbers) as requested(room_number)
    );

  if v_matched_count <> v_requested_count then
    raise exception 'One or more website rooms are inactive or do not belong to this hotel.';
  end if;

  if exists (
    select 1
    from public.physical_room_allotments pra
    where pra.hotel_id = v_hotel_id
      and (
        (pra.hold_id is not null and pra.hold_expires_at > now())
        or pra.group_block_id is not null
      )
  ) then
    raise exception 'Clear active checkout holds and group blocks before replacing the website allocation.';
  end if;

  update public.physical_rooms pr
  set web_allocation_enabled = (
    upper(pr.room_number) = any(
      select upper(btrim(room_number))
      from unnest(p_room_numbers) as requested(room_number)
    )
  )
  where pr.hotel_id = v_hotel_id;

  v_operational_date := public.hotel_operational_date(v_hotel_id);

  update public.physical_room_allotments pra
  set is_available = pr.web_allocation_enabled
  from public.physical_rooms pr
  where pr.id = pra.room_id
    and pr.hotel_id = pra.hotel_id
    and pra.hotel_id = v_hotel_id
    and pra.date >= v_operational_date
    and not pra.is_booked;

  get diagnostics v_affected_rows = row_count;

  select coalesce(max(pra.date) + 1, v_operational_date + 1)
  into v_end_date_exclusive
  from public.physical_room_allotments pra
  where pra.hotel_id = v_hotel_id
    and pra.date >= v_operational_date;

  insert into public.inventory_change_events (
    hotel_id,
    actor_user_id,
    kind,
    range_start,
    range_end_exclusive,
    affected_rows,
    reason,
    metadata
  )
  values (
    v_hotel_id,
    auth.uid(),
    'bulk_update',
    v_operational_date,
    v_end_date_exclusive,
    v_affected_rows,
    'Opening website room allocation',
    jsonb_build_object(
      'website_room_count', v_requested_count,
      'room_numbers', p_room_numbers
    )
  );

  return jsonb_build_object(
    'ok', true,
    'website_room_count', v_requested_count,
    'affected_rows', v_affected_rows,
    'range_start', v_operational_date,
    'range_end_exclusive', v_end_date_exclusive
  );
end;
$$;

revoke all on function public.apply_room_web_allocation_to_new_allotment()
  from public, anon, authenticated;
revoke all on function public.publish_initial_web_allocation(text[])
  from public, anon;

grant execute on function public.publish_initial_web_allocation(text[])
  to authenticated;

comment on column public.physical_rooms.web_allocation_enabled is
  'Whether future allotment rows for this room open for public website sale by default.';

comment on function public.publish_initial_web_allocation(text[]) is
  'Admin/manager-only replacement of the persistent physical-room website allocation; refuses to run across active holds or group blocks.';
