// Generated by the OpenNext build and available when Wrangler bundles this entry point.
import nextHandler from "./.open-next/worker.js";

interface CloudflareEnv {
  CRON_SECRET: string;
}

interface ExecutionContextLike {
  waitUntil(promise: Promise<unknown>): void;
}

const worker = {
  fetch: nextHandler.fetch,

  async scheduled(
    _event: unknown,
    env: CloudflareEnv,
    context: ExecutionContextLike,
  ) {
    const request = new Request("https://worker.internal/api/notifications/process", {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
      method: "POST",
    });

    context.waitUntil(
      nextHandler.fetch(request, env, context).then((response: Response) => {
        if (!response.ok && response.status !== 207) {
          throw new Error(`Notification worker returned HTTP ${response.status}.`);
        }
      }),
    );
  },
};

export default worker;
