#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const states = ["backlog", "ready", "active", "blocked", "review", "revision-required", "verified", "done", "cancelled", "archived"];
const limits = { packet: 16384, context: 131072, evidence: 32768, handoff: 16384, excerpt: 8192 };

const fail = (message) => { throw new Error(message); };
const now = () => new Date().toISOString();
const slash = (value) => value.replaceAll(path.sep, "/");
const write = (file, text) => { fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, text.endsWith("\n") ? text : `${text}\n`, "utf8"); };
const bytes = (file) => fs.statSync(file).size;
const checkLimit = (file, max, label) => { if (bytes(file) > max) fail(`${label} exceeds ${max} bytes: ${slash(path.relative(root, file))}`); };
const secretPattern = /-----BEGIN [A-Z ]*PRIVATE KEY-----|\b(?:sk|ghp|github_pat|xox[baprs]|sb_secret)_[A-Za-z0-9_-]{12,}\b|(?:OPENAI|STRIPE|SUPABASE|CLOUDFLARE|GITHUB)[A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD)\s*[:=]/i;
function insideRepository(absolute) { const relative = path.relative(root, absolute); if (relative.startsWith("..") || path.isAbsolute(relative)) fail("Context operation must remain inside the repository."); return relative; }

function args(values) {
  const result = {}; const valued = new Set(["task", "artifact", "from", "to", "summary", "status", "tests", "files", "model", "path", "max"]); const flags = new Set(["help", "self-test", "unverified"]);
  for (let i = 0; i < values.length; i += 1) { const item = values[i]; if (!item.startsWith("--")) fail(`Unexpected argument: ${item}`); const key = item.slice(2); if (valued.has(key)) { const value = values[++i]; if (!value || value.startsWith("--")) fail(`Missing --${key}`); result[key] = value; } else if (flags.has(key)) result[key] = true; else fail(`Unknown option: --${key}`); }
  return result;
}
function glob(pattern) { const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replaceAll("**", "::DOUBLE::").replaceAll("*", "[^/]*").replaceAll("::DOUBLE::", ".*"); return new RegExp(`^${escaped}$`); }
function matches(file, patterns) { return patterns.some((pattern) => glob(pattern).test(file)); }
function walk(directory, result = []) { if (result.length >= 250) return result; for (const entry of fs.readdirSync(directory, { withFileTypes: true })) { if ([".git", "node_modules", ".next", "dist", ".astro", "artifacts"].includes(entry.name)) continue; const absolute = path.join(directory, entry.name); if (entry.isDirectory()) walk(absolute, result); else result.push(slash(path.relative(root, absolute))); } return result; }
function git(argsToRun) { const result = spawnSync("git", argsToRun, { cwd: root, encoding: "utf8", windowsHide: true }); return result.status === 0 ? (result.stdout ?? "").trim() : ""; }
function findTask(taskId) { if (!/^[A-Za-z0-9][A-Za-z0-9._-]{2,80}$/.test(taskId)) fail("Invalid task ID."); const found = states.map((state) => ({ state, json: path.join(root, "tasks", state, taskId, "task.json"), markdown: path.join(root, "tasks", state, taskId, "TASK.md") })).filter((item) => fs.existsSync(item.json) || fs.existsSync(item.markdown)); if (found.length !== 1) fail(`Expected exactly one task packet for ${taskId}.`); const json = fs.existsSync(found[0].json); const packet = json ? JSON.parse(fs.readFileSync(found[0].json, "utf8")) : { taskId, title: taskId, status: found[0].state, allowedPaths: [], forbiddenPaths: [], architectureReferences: [], evidence: [], acceptanceCriteria: [], requiredTests: [], owner: "unknown", reviewer: "unknown", contextBudget: { maxBytes: limits.context, includedPaths: [] } }; return { ...found[0], packet, source: slash(path.relative(root, json ? found[0].json : found[0].markdown)) }; }
function contextDirectory(record) { return path.join(root, "tasks", record.state, record.packet.taskId, "context"); }
function safeRead(relative) { const absolute = path.resolve(root, relative); const inside = path.relative(root, absolute); if (inside.startsWith("..") || path.isAbsolute(inside)) fail(`Context path escapes repository: ${relative}`); return fs.existsSync(absolute) && fs.statSync(absolute).isFile() ? fs.readFileSync(absolute, "utf8") : null; }

function buildTask(taskId) {
  const record = findTask(taskId); const packet = record.packet; const directory = contextDirectory(record); fs.mkdirSync(directory, { recursive: true });
  const included = ["AGENTS.md", "docs/project/CONTEXT_INDEX.md", "docs/project/ISSUES_AND_RISKS.md", "docs/project/CONTEXT_MANAGEMENT.md", packet.evidence?.[0], ...(packet.contextBudget?.includedPaths ?? [])].filter(Boolean).filter((item, index, list) => list.indexOf(item) === index).filter((item) => safeRead(item));
  const references = (packet.architectureReferences ?? []).map((item) => `- Canonical reference (link only; charter not copied): [${item}](${item})`).join("\n") || "- None declared.";
  const taskText = ["# Task context — " + packet.taskId, "", "Generated: " + now(), "", "## Budget", "", "- Recommended context-pack maximum: " + limits.context + " bytes.", "- Only task-governance references and exact evidence links are included.", "- Canonical architecture is linked only; it is never pasted here.", "", "## Verified facts", "", "- Task: **" + packet.title + "** (" + packet.status + ").", "- Owner: " + (packet.owner ?? "unknown") + "; reviewer: " + (packet.reviewer ?? "unknown") + ".", "- Business objective: " + (packet.businessObjective ?? "not available in legacy packet"), "- Technical objective: " + (packet.technicalObjective ?? "not available in legacy packet"), "- Allowed paths: " + ((packet.allowedPaths ?? []).join(", ") || "not declared"), "- Forbidden paths: " + ((packet.forbiddenPaths ?? []).join(", ") || "not declared"), "- Required tests: " + ((packet.requiredTests ?? []).join(", ") || "not declared"), "", "## Canonical references", "", references, "", "## Interpretation", "", "This pack contains repository facts and links only. Model interpretation must be labeled in a handoff.", "", "## Unresolved decisions", "", "Review the task packet and risk register before acting; append unresolved decisions to the decisions file.", "", "## Included source references", "", included.map((item) => `- [${item}](${item})`).join("\n")].join("\n");
  write(path.join(directory, "task-context.md"), taskText);
  const allowed = (packet.allowedPaths ?? []).map((item) => "- " + item).join("\n") || "- Not declared."; const relevant = walk(root).filter((item) => matches(item, packet.allowedPaths ?? [])).slice(0, 200).map((item) => `- [${item}](${item})`).join("\n") || "- None found.";
  write(path.join(directory, "file-map.md"), ["# File map — " + packet.taskId, "", "Generated: " + now(), "", "## Allowed scope", "", allowed, "", "## Existing relevant files (names only)", "", relevant, "", "Protected paths are inspected by verification and never copied here."].join("\n"));
  write(path.join(directory, "decisions.md"), "# Decisions — " + packet.taskId + "\n\nNo unresolved decision has been recorded by the context builder. Add owner, date, options, and evidence for each decision.\n");
  write(path.join(directory, "known-risks.md"), "# Known risks — " + packet.taskId + "\n\n- [Repository risk register](../../../../docs/project/ISSUES_AND_RISKS.md)\n- Interpretations and model-generated concerns must be labeled separately from verified facts.\n");
  write(path.join(directory, "latest-handoff.md"), "# Latest handoff — " + packet.taskId + "\n\nNo handoff has been recorded. Use the context build-handoff command at a role boundary.\n");
  write(path.join(directory, "artifact-index.md"), "# Artifact index — " + packet.taskId + "\n\nRaw logs remain in artifacts and are referenced, not pasted.\n\n" + ((packet.evidence ?? []).map((item) => `- [${item}](${item})`).join("\n") || "- No evidence references declared.") + "\n");
  for (const file of ["task-context.md", "file-map.md", "decisions.md", "known-risks.md", "latest-handoff.md", "artifact-index.md"]) checkLimit(path.join(directory, file), limits.context, "Context file");
  return { taskId, contextDirectory: slash(path.relative(root, directory)), includedFiles: included.length };
}
function buildReview(taskId) { const record = findTask(taskId); const directory = contextDirectory(record); const changed = git(["diff", "--name-only"]) || "(no uncommitted changes)"; const content = ["# Independent review context — " + taskId, "", "Generated: " + now(), "", "## Role boundary", "", "This is a fresh reviewer context. Do not import implementer conversation, assumptions, or self-reported completion.", "", "## Verified inputs", "", "- Task packet: [" + record.source + "](" + record.source + ")", "- Acceptance criteria: " + ((record.packet.acceptanceCriteria ?? []).join("; ") || "not declared"), "- Verification policy: [VERIFICATION_POLICY.md](../../../../docs/verification/VERIFICATION_POLICY.md)", "", "## Final diff names", "", changed.split(/\r?\n/).map((item) => "- " + item).join("\n"), "", "## Reviewer interpretation", "", "Add only after independent inspection.", "", "## Remaining context budget", "", limits.context + " bytes maximum for this pack."].join("\n"); const file = path.join(directory, "review-context.md"); write(file, content); checkLimit(file, limits.context, "Review context"); return { taskId, file: slash(path.relative(root, file)) }; }
function buildHandoff(options) { const record = findTask(options.task); const changed = options.files ?? (git(["diff", "--name-only"]) || "none recorded"); const tests = options.tests ?? "none recorded"; if (secretPattern.test(options.summary ?? "")) fail("Potential secret detected in handoff summary; nothing was written."); const changedItems = changed.split(/\r?\n|,/).filter(Boolean); const testItems = tests.split(/\r?\n|,/).filter(Boolean); const content = ["# Handoff — " + record.packet.taskId, "", "- From: " + options.from, "- To: " + options.to, "- Status: " + (options.status ?? "in-progress"), "- Created: " + now(), "- Remaining context budget: " + limits.handoff + " bytes maximum", "", "## Verified facts", "", "- Task packet: [" + record.source + "](" + record.source + ")", "- Files changed:", changedItems.map((item) => "  - " + item.trim()).join("\n"), "- Tests/checks run:", testItems.map((item) => "  - " + item.trim()).join("\n"), "", "## Interpretation", "", options.summary ?? "No interpretation recorded.", "", "## Unresolved decisions and risks", "", "- None recorded; receiver must inspect the task packet and evidence.", "", "## Evidence", "", "- Raw logs remain artifact references. Exact errors and failures must be linked, not paraphrased away."].join("\n"); const directory = contextDirectory(record); const contextFile = path.join(directory, "latest-handoff.md"); write(contextFile, content); const durable = path.join(root, "docs", "handoffs", record.packet.taskId + "-" + Date.now() + ".md"); write(durable, content); checkLimit(contextFile, limits.handoff, "Handoff"); checkLimit(durable, limits.handoff, "Handoff"); return { taskId: record.packet.taskId, contextFile: slash(path.relative(root, contextFile)), durableFile: slash(path.relative(root, durable)) }; }
function summarizeArtifact(options) { const artifact = path.resolve(root, options.artifact); const relativeArtifact = insideRepository(artifact); if (!relativeArtifact.startsWith(`artifacts${path.sep}`) && !relativeArtifact.startsWith("artifacts/")) fail("Only files under artifacts/ may be summarized."); if (!fs.existsSync(artifact) || !fs.statSync(artifact).isFile()) fail("Artifact not found: " + options.artifact); const original = fs.readFileSync(artifact, "utf8"); if (secretPattern.test(original)) fail("Potential secret detected; summary was not written. Preserve the original securely and escalate."); const exact = original.split(/\r?\n/).filter((line) => /error|fail|exception|stack|at\s+\S+\s*\(/i.test(line)).slice(0, 80).join("\n").slice(0, limits.excerpt); const label = options.unverified ? "UNVERIFIED PREPROCESSING (Qwen/local model; requires verification)" : "Deterministic artifact reduction (not semantic verification)"; const output = ["# Artifact summary", "", "- Original: " + slash(relativeArtifact), "- Original bytes: " + Buffer.byteLength(original), "- Summary mode: " + label, "- Exact error/failure excerpt is preserved below; original remains authoritative.", "", "## Exact excerpt", "", "~~~text", exact || original.slice(-limits.excerpt), "~~~", "", "## Interpretation", "", "No semantic interpretation was generated."].join("\n"); const destination = path.join(root, "artifacts", "reports", path.basename(artifact) + ".summary.md"); write(destination, output); checkLimit(destination, limits.evidence, "Artifact summary"); return { artifact: slash(relativeArtifact), summary: slash(path.relative(root, destination)), originalBytes: Buffer.byteLength(original) }; }
function checkContext(paths, max) { const requested = paths.length ? paths.map((item) => { const absolute = path.resolve(root, item); insideRepository(absolute); return absolute; }) : walk(root).filter((item) => item.includes("/context/")).map((item) => path.resolve(root, item)); const files = requested.flatMap((item) => { if (!fs.existsSync(item)) return []; if (fs.statSync(item).isFile()) return [item]; return walk(item, []).filter((relative) => relative.includes("/context/") || path.basename(item) === "context").map((relative) => path.resolve(root, relative)); }); const results = files.map((item) => ({ path: slash(path.relative(root, item)), bytes: bytes(item), max, passed: bytes(item) <= max })); return { passed: results.every((item) => item.passed), results }; }
function selfTest() { const fixture = fs.mkdtempSync(path.join(os.tmpdir(), "sut-aios-context-selftest-")); try { const file = path.join(fixture, "log.txt"); fs.writeFileSync(file, "ERROR exact failure\n at fixture (x.js:1:1)\n"); if (!glob("scripts/context/**").test("scripts/context/x.mjs") || !/ERROR exact failure/.test(fs.readFileSync(file, "utf8"))) fail("Context self-test failed."); process.stdout.write(JSON.stringify({ status: "passed", checks: 3 }) + "\n"); } finally { fs.rmSync(fixture, { recursive: true, force: true }); } }
function main() { const command = path.basename(process.argv[1]); const options = args(process.argv.slice(2)); if (options.help) { process.stdout.write("Usage: node scripts/context/<command> --task <id> | --artifact <path> | --path <path>\n"); return; } if (options["self-test"]) return selfTest(); if (command === "build-task-context") return process.stdout.write(JSON.stringify(buildTask(options.task), null, 2) + "\n"); if (command === "build-review-context") return process.stdout.write(JSON.stringify(buildReview(options.task), null, 2) + "\n"); if (command === "build-handoff") { if (!options.task || !options.from || !options.to) fail("build-handoff requires --task, --from, and --to"); return process.stdout.write(JSON.stringify(buildHandoff(options), null, 2) + "\n"); } if (command === "summarize-artifact") return process.stdout.write(JSON.stringify(summarizeArtifact(options), null, 2) + "\n"); if (command === "check-context-size") { const result = checkContext(options.path ? [options.path] : [], Number(options.max) || limits.context); process.stdout.write(JSON.stringify(result, null, 2) + "\n"); if (!result.passed) process.exitCode = 1; return; } fail("Unknown context command: " + command); }
main();
