#!/usr/bin/env node
import { spawnSync } from "node:child_process";
import os from "node:os";
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const maxInputBytes = 262144; const timeoutMs = 120000; const promptVersion = "local-qwen-preprocess-v1";
const operations = new Set(["repo-map", "summarize-module", "classify-logs", "redact-evidence", "compare-schemas", "summarize-diff", "draft-fixtures", "check-content"]);
const secretPattern = /-----BEGIN [A-Z ]*PRIVATE KEY-----|\b(?:sk|ghp|github_pat|xox[baprs]|sb_secret)_[A-Za-z0-9_-]{12,}\b|(?:OPENAI|STRIPE|SUPABASE|CLOUDFLARE|GITHUB)[A-Z0-9_]*(?:KEY|TOKEN|SECRET|PASSWORD)\s*[:=]/i;
const piiPatterns = [/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi, /\b(?:\+?66|0)\d[\d -]{7,}\b/g, /\b\d{13}\b/g];
function fail(message) { throw new Error(message); }
function now() { return new Date().toISOString(); }
function parseArgs(values) { const out = {}; const valued = new Set(["input", "model", "provider", "task"]); const flags = new Set(["help", "self-test"]); for (let i = 0; i < values.length; i += 1) { const item = values[i]; if (!item.startsWith("--")) fail(`Unexpected argument: ${item}`); const key = item.slice(2); if (valued.has(key)) { const value = values[++i]; if (!value || value.startsWith("--")) fail(`Missing --${key}`); out[key] = value; } else if (flags.has(key)) out[key] = true; else fail(`Unknown option: --${key}`); } return out; }
function executable(name) { const command = process.platform === "win32" ? "where" : "which"; const result = spawnSync(command, [name], { encoding: "utf8", windowsHide: true, timeout: 5000 }); return result.status === 0 ? (result.stdout ?? "").split(/\r?\n/)[0].trim() : null; }
function commandAudit(name, argsToRun) { const found = executable(name); if (!found) return { installed: false, command: name }; const result = spawnSync(name, argsToRun, { encoding: "utf8", windowsHide: true, timeout: 5000 }); return { installed: true, command: found, status: result.status, version: (result.stdout || result.stderr || "").trim().slice(0, 300) }; }
function fileCandidates() { const home = os.homedir(); const dirs = [path.join(home, ".ollama", "models"), path.join(home, "AppData", "Local", "LM Studio", "models"), path.join(home, ".cache", "huggingface"), path.join(home, "models")]; const found = []; for (const directory of dirs) { if (!fs.existsSync(directory)) continue; const stack = [directory]; while (stack.length && found.length < 100) { const current = stack.pop(); for (const entry of fs.readdirSync(current, { withFileTypes: true })) { const absolute = path.join(current, entry.name); if (entry.isDirectory()) stack.push(absolute); else if (/(qwen|gguf|safetensors)/i.test(entry.name)) found.push({ path: absolute, bytes: fs.statSync(absolute).size }); } } } return found; }
function hardware() { const disks = []; for (const drive of process.platform === "win32" ? ["C:\\", "E:\\"] : [os.homedir()]) { try { const stat = fs.statfsSync(drive); disks.push({ path: drive, freeBytes: stat.bavail * stat.bsize, totalBytes: stat.blocks * stat.bsize }); } catch { /* unavailable on this platform */ } } return { os: `${process.platform}/${process.arch}`, cpu: os.cpus()[0]?.model ?? "unknown", logicalCpus: os.cpus().length, ramBytes: os.totalmem(), freeRamBytes: os.freemem(), disks, gpu: "not safely discoverable by cross-platform Node audit" }; }
function health() { const started = Date.now(); const provider = process.env.SUT_QWEN_PROVIDER ?? "not-configured"; const model = process.env.SUT_QWEN_MODEL ?? "not-selected"; const runtimes = { ollama: commandAudit("ollama", ["--version"]), lmStudio: commandAudit("lms", ["--version"]), llamaCpp: commandAudit("llama-server", ["--version"]), vllm: commandAudit("vllm", ["--version"]), llamafile: commandAudit("llamafile", ["--version"]) }; const result = { schemaVersion: "1.0.0", runId: crypto.randomUUID(), operation: "health", status: "completed", model: { provider, id: model, version: model === "not-selected" ? "not-selected" : "configured-id-only" }, promptVersion, inputBytes: 0, piiMasked: true, verified: false, unverifiedLabel: "Local runtime/model health is observational and unverified.", productionEligible: false, output: { hardware: hardware(), runtimes, qwenModelFiles: fileCandidates(), storageWasChecked: true }, validation: { passed: true, checks: ["No model identifier guessed", "No model files modified", "No production credentials loaded", "Read-only runtime inspection"] }, startedAt: new Date(started).toISOString(), finishedAt: now(), durationMs: Date.now() - started }; return result; }
function safeInput(file) { const absolute = path.resolve(root, file); const relative = path.relative(root, absolute); if (relative.startsWith("..") || path.isAbsolute(relative)) fail("Input must remain inside this repository."); if (relative.startsWith("reference/") || /(^|[\\/])\.env|secret|credential|key/i.test(relative)) fail("Protected or secret-like input path refused."); if (!fs.existsSync(absolute) || !fs.statSync(absolute).isFile()) fail("Input file not found."); if (fs.statSync(absolute).size > maxInputBytes) fail(`Input exceeds ${maxInputBytes} bytes.`); return absolute; }
function mask(text) { let output = text; for (const pattern of piiPatterns) output = output.replace(pattern, "[PII-REDACTED]"); return output; }
function resultBlocked(operation, inputBytes, reason) { const timestamp = now(); return { schemaVersion: "1.0.0", runId: crypto.randomUUID(), operation, status: "blocked", reason, model: { provider: process.env.SUT_QWEN_PROVIDER ?? "not-configured", id: process.env.SUT_QWEN_MODEL ?? "not-selected", version: "not-verified" }, promptVersion, inputBytes, piiMasked: true, verified: false, unverifiedLabel: "Qwen/local preprocessing is unverified and cannot be evidence or authority.", productionEligible: false, validation: { passed: true, checks: ["Structured result shape", "Read-only default", "No shell generation", "No production/database access"] }, startedAt: timestamp, finishedAt: now(), durationMs: 0 }; }
function operation(name, options) { if (!operations.has(name)) fail(`Unknown local-ai operation: ${name}`); if (!options.input) fail(`${name} requires --input <repository-file>.`); const file = safeInput(options.input); const original = fs.readFileSync(file, "utf8"); const masked = mask(original); if (secretPattern.test(masked)) return resultBlocked(name, Buffer.byteLength(original), "Potential secret material remains after PII masking; manual redaction required."); const healthResult = health(); if (!healthResult.output.runtimes.ollama.installed && !healthResult.output.runtimes.lmStudio.installed) return resultBlocked(name, Buffer.byteLength(original), "No Ollama or LM Studio runtime is installed; no model identifier was guessed."); if (!options.model && !process.env.SUT_QWEN_MODEL) return resultBlocked(name, Buffer.byteLength(original), "No explicit Qwen model identifier supplied; wrapper will not guess one."); return resultBlocked(name, Buffer.byteLength(masked), "Runtime detected but execution requires a separately verified provider invocation profile."); }
function benchmark() { const started = Date.now(); const records = ["qwen-local", "gpt-5.6-luna", "gpt-5.6-terra"].map((model) => ({ model, tasks: ["repository summarization", "log classification", "schema comparison", "diff summarization"].map((task) => ({ task, correctness: "not_run", durationMs: 0, verificationSuccess: false, status: "blocked" })), reason: model === "qwen-local" ? "No runtime/model identifier available." : "Hosted Codex benchmark execution is not available in this local sidecar." })); return { schemaVersion: "1.0.0", runId: crypto.randomUUID(), operation: "benchmark", status: "completed", model: { provider: "none", id: "not-selected", version: "not-selected" }, promptVersion, inputBytes: 0, piiMasked: true, verified: false, unverifiedLabel: "Benchmark records availability only; no correctness claim is made.", productionEligible: false, output: { hardware: hardware(), records }, validation: { passed: true, checks: ["All four benchmark task labels present", "Qwen model identifier not guessed", "No downloads performed", "Blocked runs not counted as correct"] }, startedAt: new Date(started).toISOString(), finishedAt: now(), durationMs: Date.now() - started }; }
function validateResult(result) { const required = ["schemaVersion", "runId", "operation", "status", "model", "promptVersion", "inputBytes", "piiMasked", "verified", "productionEligible", "validation", "startedAt", "finishedAt"]; for (const key of required) if (!(key in result)) fail(`Local AI result missing ${key}.`); if (result.schemaVersion !== "1.0.0" || !result.model.id || result.verified || result.productionEligible || result.inputBytes > maxInputBytes) fail("Local AI result failed deterministic safety validation."); return result; }
function selfTest() { const masked = mask("guest@example.com 0812345678"); if (masked.includes("guest@example.com") || !masked.includes("PII-REDACTED")) fail("PII masking self-test failed."); const result = resultBlocked("self-test", 10, "fixture"); if (result.verified || result.productionEligible || result.status !== "blocked") fail("result safety self-test failed."); process.stdout.write(JSON.stringify({ status: "passed", checks: 4 }) + "\n"); }
function main() { const command = path.basename(process.argv[1]); const options = parseArgs(process.argv.slice(2)); if (options.help) { process.stdout.write("Usage: node scripts/local-ai/<operation> [--input path] | node scripts/local-ai/health | benchmark\n"); return; } if (options["self-test"]) return selfTest(); let result; if (command === "health") result = health(); else if (command === "benchmark") result = benchmark(); else result = operation(command, options); process.stdout.write(`${JSON.stringify(validateResult(result), null, 2)}\n`); }
main();
