#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const reportDir = path.join(root, "artifacts", "reports", "model-runs");
const forbidden = /-----BEGIN [A-Z ]*PRIVATE KEY-----|\b(?:ghp|github_pat|sk|xox[baprs]|sb_secret)_[A-Za-z0-9_-]{12,}\b|(?:password|secret|credential|access[_-]?token)\s*[:=]/i;
const usage = "Usage: model-run:<record|report|compare|recommend-routing> --input <sanitized-json> [--output <report.json>]";
function fail(message) { throw new Error(message); }
function args(values) { const result = {}; for (let i = 0; i < values.length; i += 1) { const key = values[i]; if (key === "--self-test") { result.selfTest = true; continue; } if (!key.startsWith("--")) fail(`Unexpected argument: ${key}`); const value = values[++i]; if (!value || value.startsWith("--")) fail(`Missing value for ${key}`); result[key.slice(2)] = value; } return result; }
function safeRead(file) { const resolved = path.resolve(root, file); if (!resolved.startsWith(root + path.sep)) fail("Input must be inside the repository."); const text = fs.readFileSync(resolved, "utf8"); if (forbidden.test(text)) fail("Input contains a secret-like value and was rejected."); return JSON.parse(text); }
function validateRun(r) { const required = ["schemaVersion", "runId", "taskId", "agentId", "model", "startedAt", "finishedAt", "durationMs", "usage", "filesInspected", "filesChanged", "commandsRun", "checksPassed", "checksFailed", "reworkRequired", "escalationRequired", "finalTaskStatus", "independentVerificationStatus", "humanInterventionRequired"]; for (const key of required) if (!(key in r)) fail(`Missing ${key}`); if (r.schemaVersion !== "1.0.0" || !/^[A-Za-z0-9._-]{8,160}$/.test(r.runId)) fail("Invalid schemaVersion or runId."); if (!Number.isInteger(r.durationMs) || r.durationMs < 0) fail("durationMs must be a non-negative integer."); for (const key of ["filesInspected", "filesChanged", "commandsRun", "checksPassed", "checksFailed"]) if (!Array.isArray(r[key])) fail(`${key} must be an array.`); const textual = JSON.stringify(r); if (forbidden.test(textual)) fail("Record contains a secret-like value and was rejected."); return r; }
function listRuns(input) { if (input) { const data = safeRead(input); return Array.isArray(data) ? data.map(validateRun) : [validateRun(data)]; } if (!fs.existsSync(reportDir)) return []; return fs.readdirSync(reportDir).filter((x) => x.endsWith(".json") && x.startsWith("run-")).map((x) => validateRun(JSON.parse(fs.readFileSync(path.join(reportDir, x), "utf8")))); }
function tokens(r) { return [r.usage?.inputTokens, r.usage?.outputTokens, r.usage?.cachedTokens].reduce((sum, n) => sum + (Number.isInteger(n) ? n : 0), 0); }
function ratio(n, d) { return d ? Number((n / d).toFixed(4)) : null; }
function metrics(runs) { const verified = runs.filter((r) => r.finalTaskStatus === "completed" && r.independentVerificationStatus === "pass"); const qwen = runs.filter((r) => /qwen/i.test(r.model) && r.outputAccepted !== null && r.outputAccepted !== undefined); const byModel = {}; for (const r of runs) { const item = byModel[r.model] ??= { runs: 0, verified: 0, tokens: 0, durationMs: 0, rework: 0, escalations: 0 }; item.runs++; item.verified += verified.includes(r) ? 1 : 0; item.tokens += tokens(r); item.durationMs += r.durationMs; item.rework += r.reworkRequired ? 1 : 0; item.escalations += r.escalationRequired ? 1 : 0; }
  return { schemaVersion: "1.0.0", generatedAt: new Date().toISOString(), runCount: runs.length, metrics: { verifiedTasksCompleted: new Set(verified.map((r) => r.taskId)).size, firstPassVerificationRate: ratio(verified.filter((r) => !r.reworkRequired).length, verified.length), revisionRate: ratio(runs.filter((r) => r.reworkRequired).length, runs.length), escalationRate: ratio(runs.filter((r) => r.escalationRequired).length, runs.length), rollbackRate: ratio(runs.filter((r) => r.finalTaskStatus === "rolled_back").length, runs.length), tokensPerVerifiedTask: verified.length ? Math.round(verified.reduce((s, r) => s + tokens(r), 0) / new Set(verified.map((r) => r.taskId)).size) : null, tokensSpentOnRework: runs.filter((r) => r.reworkRequired).reduce((s, r) => s + tokens(r), 0), lunaToTerraEscalations: runs.filter((r) => r.escalation?.fromModel === "gpt-5.6-luna" && r.escalation?.toModel === "gpt-5.6-terra").length, terraToSolEscalations: runs.filter((r) => r.escalation?.fromModel === "gpt-5.6-terra" && r.escalation?.toModel === "gpt-5.6-sol").length, qwenOutputAcceptanceRate: ratio(qwen.filter((r) => r.outputAccepted).length, qwen.length), defectsFoundAfterMerge: runs.filter((r) => r.defectFoundAfterMerge).length }, byModel, privacyNotice: "Aggregate metadata only. Prompts, model output, credentials, guest data, and raw logs are prohibited." }; }
function write(result, output) { if (!output) return process.stdout.write(`${JSON.stringify(result, null, 2)}\n`); const target = path.resolve(root, output); if (!target.startsWith(reportDir + path.sep)) fail("Reports may be written only under artifacts/reports/model-runs/."); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, `${JSON.stringify(result, null, 2)}\n`); process.stdout.write(`${JSON.stringify({ status: "written", output: path.relative(root, target).replaceAll(path.sep, "/") })}\n`); }
function selfTest() { const run = validateRun({ schemaVersion: "1.0.0", runId: "run-selftest-001", taskId: "SUT-TEST-001", agentId: "qa-verification", model: "gpt-5.6-terra", reasoningLevel: "medium", startedAt: "2026-01-01T00:00:00.000Z", finishedAt: "2026-01-01T00:00:01.000Z", durationMs: 1000, usage: { inputTokens: 10, outputTokens: 5, cachedTokens: 0 }, filesInspected: ["docs/x.md"], filesChanged: [], commandsRun: ["node --version"], checksPassed: ["fixture"], checksFailed: [], reworkRequired: false, escalationRequired: false, finalTaskStatus: "completed", independentVerificationStatus: "pass", humanInterventionRequired: false, outputAccepted: null, defectFoundAfterMerge: false }); const report = metrics([run]); if (report.metrics.verifiedTasksCompleted !== 1 || report.metrics.tokensPerVerifiedTask !== 15) fail("Self-test metric mismatch."); process.stdout.write(`${JSON.stringify({ status: "passed", checks: 4 })}\n`); }
function main() { const command = path.basename(process.argv[1]); const o = args(process.argv.slice(2)); if (o.selfTest) return selfTest(); if (command === "record") { const run = validateRun(safeRead(o.input)); const target = path.join(reportDir, `${run.runId}.json`); if (fs.existsSync(target)) fail("Run ID already exists; records are immutable."); fs.mkdirSync(reportDir, { recursive: true }); fs.writeFileSync(target, `${JSON.stringify(run, null, 2)}\n`); return process.stdout.write(`${JSON.stringify({ status: "recorded", run: path.relative(root, target).replaceAll(path.sep, "/") })}\n`); } const report = metrics(listRuns(o.input)); if (command === "report" || command === "compare") return write(report, o.output); if (command === "recommend-routing") { const recommendations = Object.entries(report.byModel).map(([model, x]) => ({ model, evidence: x, recommendation: x.runs < 3 ? "insufficient-data" : x.rework / x.runs > 0.3 ? "consider-escalation-or-narrower-scope" : "continue-observation" })); return write({ ...report, advisoryOnly: true, recommendations, policyMutation: "prohibited" }, o.output); } fail(usage); }
main();
